### ISSUE TITLE
Design BD structure

### ISSUE THREAD

**Issue by Zomba4okk** [Zomba4okk/DjangoOnlinerLikeShop#12]
Design and describe BD structure using any suitable application and pin the result to this task.

Our web application should provide 4 different functions for users:
- Show news. Each news object should have a title, description, and one or many images. Users should be available to like and dislike news.
- Provide a catalog of different products. Products should be divided into subcategories, which in turn should be divided into categories. Each product should have a name, description, characteristics (as a text field), and price. Authorized users should be allowed to save products into the cart and to create orders from products stored in this cart.

- Users should be able to view and create advertisements for the purchase/sale of real estate. Each advertisement object should have a title, description, type (purchase/sale), one or many images, coordinates (latitude and longitude) for google maps, address, owner contacts, price (owner should be able to set any concrete price or value that mean negotiated price) and link to the user - owner. 

- Users should be able to view and create advertisements for the provision of any services. Each advertisement object should have a title, description, contacts, price (as text field, to allow the user to indicate the price and calculation method. E.g. '10$ each hour' or '100$ for one day', or '30 BYN per square meter') and link to the user - owner.

- User data should be stored in two tables: **main** user table with, email (as username), password hash, is_activated flag (the only user that confirmed email can use it's account), is_deleted flag (to not remove deleted users from DB), account_type (to implement different permissions), registration_date and any other technical info.  Additional **profile** table should store personal info: phone, first name, last name, middle name, address, date of birth, sex, photo, etc.

**Comment by borisoid** [comment]
Made a draft of db structure.
Came up with solution to the problem of different filters for different product categories, though it requires db level typecast, so it might become even more of a problem. We'll probably end up not using it. In this case we just need to drop "ProductSpec" and "CategoryProperty" tables.
I've got some questions about real estate purchase/sale announcement and service announcement details, but it'd be better to discuss in Skype.
![Untitled Diagram](https://user-images.githubusercontent.com/54960216/108899612-ae017580-7629-11eb-8794-dae36c078d29.png)

**Comment by borisoid** [comment]
Made a complete DB structure diagram.
![Untitled Diagram (1)](https://user-images.githubusercontent.com/54960216/109151756-a225c880-777b-11eb-9511-d8f1bb1dfdfc.png)
